version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_pet_project
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge
